# Generated by Django 5.0.4 on 2024-05-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0014_tag_quiz_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
