# Generated by Django 5.0.3 on 2024-05-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0017_alter_quiz_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Moderately Easy'), (3, 'Intermediate'), (4, 'Moderately Hard'), (5, 'Hard')], default=1),
        ),
    ]
