# Generated by Django 5.0.3 on 2024-05-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0020_quiz_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Moderately Easy', 'Moderately Easy'), ('Intermediate', 'Intermediate'), ('Moderately Hard', 'Moderately Hard'), ('Hard', 'Hard')], default='Easy', max_length=20),
        ),
    ]
